/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mashgeneraldealer;

/**
 *
 * @author RT19001209
 */
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingBanner = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        logout = new java.awt.Button();
        adminPanel = new javax.swing.JPanel();
        adminWelcomeMessage = new javax.swing.JLabel();
        adminTasks = new javax.swing.JLabel();
        addRemoveStock = new java.awt.Button();
        inventoryCheck = new java.awt.Button();
        manageUsers = new java.awt.Button();
        inventoryCheck1 = new java.awt.Button();
        passwordChange = new java.awt.Button();
        dateStamp = new javax.swing.JLabel();
        timeStamp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        headingBanner.setBackground(new java.awt.Color(187, 161, 209));

        heading.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heading.setText("MASH GENERAL DEALER");

        logout.setBackground(new java.awt.Color(217, 162, 246));
        logout.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        logout.setLabel("Logout");

        javax.swing.GroupLayout headingBannerLayout = new javax.swing.GroupLayout(headingBanner);
        headingBanner.setLayout(headingBannerLayout);
        headingBannerLayout.setHorizontalGroup(
            headingBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headingBannerLayout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        headingBannerLayout.setVerticalGroup(
            headingBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headingBannerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headingBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        adminPanel.setBackground(new java.awt.Color(217, 111, 246));

        adminWelcomeMessage.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        adminWelcomeMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminWelcomeMessage.setText("Welcome admin");

        adminTasks.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        adminTasks.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        adminTasks.setText("What would you like to do?");

        addRemoveStock.setBackground(new java.awt.Color(217, 162, 246));
        addRemoveStock.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        addRemoveStock.setLabel("Add or remove stock");
        addRemoveStock.setMaximumSize(new java.awt.Dimension(57, 24));

        inventoryCheck.setBackground(new java.awt.Color(217, 162, 246));
        inventoryCheck.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        inventoryCheck.setLabel("Manage users");
        inventoryCheck.setMaximumSize(new java.awt.Dimension(119, 31));

        manageUsers.setBackground(new java.awt.Color(217, 162, 246));
        manageUsers.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        manageUsers.setLabel("Check Inventory");
        manageUsers.setMaximumSize(new java.awt.Dimension(136, 31));

        inventoryCheck1.setBackground(new java.awt.Color(217, 162, 246));
        inventoryCheck1.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        inventoryCheck1.setLabel("View Reports");
        inventoryCheck1.setMaximumSize(new java.awt.Dimension(119, 31));

        passwordChange.setBackground(new java.awt.Color(217, 162, 246));
        passwordChange.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        passwordChange.setLabel("Change Password");
        passwordChange.setMaximumSize(new java.awt.Dimension(119, 31));

        dateStamp.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        dateStamp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dateStamp.setText("DATE");

        timeStamp.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        timeStamp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        timeStamp.setText("TIME");

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inventoryCheck1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addRemoveStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(87, 87, 87)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(manageUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordChange, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addComponent(inventoryCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(timeStamp, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(adminPanelLayout.createSequentialGroup()
                            .addGap(191, 191, 191)
                            .addComponent(adminWelcomeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dateStamp, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(adminPanelLayout.createSequentialGroup()
                            .addGap(255, 255, 255)
                            .addComponent(adminTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminWelcomeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateStamp, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeStamp, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addRemoveStock, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inventoryCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inventoryCheck1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordChange, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headingBanner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(adminPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headingBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 469, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(adminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button addRemoveStock;
    private javax.swing.JPanel adminPanel;
    private javax.swing.JLabel adminTasks;
    private javax.swing.JLabel adminWelcomeMessage;
    private javax.swing.JLabel dateStamp;
    private javax.swing.JLabel heading;
    private javax.swing.JPanel headingBanner;
    private java.awt.Button inventoryCheck;
    private java.awt.Button inventoryCheck1;
    private java.awt.Button logout;
    private java.awt.Button manageUsers;
    private java.awt.Button passwordChange;
    private javax.swing.JLabel timeStamp;
    // End of variables declaration//GEN-END:variables
}
